/*
 * Generated by erpcgen 1.13.0 on Fri Aug 30 12:29:51 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_erpc_servo_configure_client_h_)
#define _c_erpc_servo_configure_client_h_

#include "erpc_servo_configure_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief ServoConfigureService identifiers */
enum _ServoConfigureService_ids
{
    kServoConfigureService_service_id = 1,
    kServoConfigureService_getAdcRaw_id = 1,
    kServoConfigureService_getAdcSinCosRaw_id = 2,
    kServoConfigureService_getAdcCurrentRaw_id = 3,
    kServoConfigureService_getAdcVoltageRaw_id = 4,
    kServoConfigureService_sdoLoadFactorySettings_id = 5,
    kServoConfigureService_sdoEntryLoadFactorySettings_id = 6,
    kServoConfigureService_sdoSubEntryLoadFactorySettings_id = 7,
    kServoConfigureService_setSdoSubEntry_id = 8,
    kServoConfigureService_getSdoSubEntry_id = 9,
    kServoConfigureService_saveAllToNonVolatileMemory_id = 10,
    kServoConfigureService_loadAllFromNonVolatileMemory_id = 11,
    kServoConfigureService_sdoSubEntrySaveToNonVolatileMemory_id = 12,
    kServoConfigureService_sdoSubEntryLoadFromNonVolatileMemory_id = 13,
};

//! @name ServoConfigureService
//@{
int32_t getAdcRaw(ErpcAdcType adcType, int32_t * value);

int32_t getAdcSinCosRaw(int32_t * sin, int32_t * cos);

int32_t getAdcCurrentRaw(int32_t * a, int32_t * b, int32_t * c);

int32_t getAdcVoltageRaw(int32_t * a, int32_t * b, int32_t * c);

int32_t sdoLoadFactorySettings(void);

int32_t sdoEntryLoadFactorySettings(uint16_t index);

int32_t sdoSubEntryLoadFactorySettings(uint16_t index, uint8_t subIndex);

int32_t setSdoSubEntry(uint16_t index, const SdoSubEntry * subEntry);

int32_t getSdoSubEntry(uint16_t index, uint8_t subIndex, SdoSubEntry * subEntry);

int32_t saveAllToNonVolatileMemory(void);

int32_t loadAllFromNonVolatileMemory(void);

int32_t sdoSubEntrySaveToNonVolatileMemory(uint16_t index, uint8_t subIndex);

int32_t sdoSubEntryLoadFromNonVolatileMemory(uint16_t index, uint8_t subIndex);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initServoConfigureService_client(erpc_client_t client);

void deinitServoConfigureService_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_erpc_servo_configure_client_h_
