/*
 * Generated by erpcgen 1.13.0 on Thu Aug 29 13:52:21 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_erpc_servo_configure_client_h_)
#define _c_erpc_servo_configure_client_h_

#include "erpc_servo_configure_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief ServoConfigureService identifiers */
enum _ServoConfigureService_ids
{
    kServoConfigureService_service_id = 1,
    kServoConfigureService_setSdoSubEntry_id = 1,
    kServoConfigureService_sdoLoadFactorySettings_id = 2,
    kServoConfigureService_sdoEntryLoadFactorySettings_id = 3,
    kServoConfigureService_sdoSubEntryLoadFactorySettings_id = 4,
    kServoConfigureService_getSdoSubEntry_id = 5,
    kServoConfigureService_saveAllToNonVolatileMemory_id = 6,
};

//! @name ServoConfigureService
//@{
int32_t setSdoSubEntry(uint16_t index, const SdoSubEntry * subEntry);

int32_t sdoLoadFactorySettings(void);

int32_t sdoEntryLoadFactorySettings(uint16_t index);

int32_t sdoSubEntryLoadFactorySettings(uint16_t index, uint8_t subIndex);

int32_t getSdoSubEntry(uint16_t index, uint8_t subIndex, SdoSubEntry * subEntry);

int32_t saveAllToNonVolatileMemory(void);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initServoConfigureService_client(erpc_client_t client);

void deinitServoConfigureService_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_erpc_servo_configure_client_h_
