/*
 * Generated by erpcgen 1.13.0 on Wed Aug 28 14:22:23 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_erpc_servo_configure_server_h_)
#define _c_erpc_servo_configure_server_h_

#include "erpc_servo_configure_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief ServoConfigureService identifiers */
enum _ServoConfigureService_ids
{
    kServoConfigureService_service_id = 1,
    kServoConfigureService_getSdoSubEntry_id = 1,
};

//! @name ServoConfigureService
//@{
int32_t getSdoSubEntry(int16_t index, int16_t subIndex, SdoSubEntry * subEntry);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return ServoConfigureService_service service object. */
erpc_service_t create_ServoConfigureService_service(void);

/*! @brief Destroy ServoConfigureService_service service object. */
void destroy_ServoConfigureService_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_erpc_servo_configure_server_h_
