/*
 * Generated by erpcgen 1.13.0 on Wed Aug 28 14:22:23 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_servo_configure_client_hpp_)
#define _erpc_servo_configure_client_hpp_

#include "erpc_servo_configure_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class ServoConfigureService_client: public ServoConfigureService_interface
{
    public:
        ServoConfigureService_client(erpc::ClientManager *manager);

        virtual ~ServoConfigureService_client();

        virtual int32_t getSdoSubEntry(int16_t index, int16_t subIndex, SdoSubEntry * subEntry);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _erpc_servo_configure_client_hpp_
