/*
 * Generated by erpcgen 1.13.0 on Thu Aug 29 09:19:44 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "erpc_servo_configure_interface.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

ServoConfigureService_interface::~ServoConfigureService_interface(void)
{
}
