/*
 * Generated by erpcgen 1.13.0 on Thu Aug 29 13:52:21 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_servo_configure_client_hpp_)
#define _erpc_servo_configure_client_hpp_

#include "erpc_servo_configure_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class ServoConfigureService_client: public ServoConfigureService_interface
{
    public:
        ServoConfigureService_client(erpc::ClientManager *manager);

        virtual ~ServoConfigureService_client();

        virtual int32_t setSdoSubEntry(uint16_t index, const SdoSubEntry * subEntry);

        virtual int32_t sdoLoadFactorySettings(void);

        virtual int32_t sdoEntryLoadFactorySettings(uint16_t index);

        virtual int32_t sdoSubEntryLoadFactorySettings(uint16_t index, uint8_t subIndex);

        virtual int32_t getSdoSubEntry(uint16_t index, uint8_t subIndex, SdoSubEntry * subEntry);

        virtual int32_t saveAllToNonVolatileMemory(void);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _erpc_servo_configure_client_hpp_
